Support new CIP37 address
Conflux-Chain/java-conflux-sdk pull request #18
Opened 2021-01-22 03:27 UTC by Pana

Check CHANGELOG for updates

2021-01-25 03:52 UTC, Tigo9527 reviewed
An `throws Exception` signature is added to multiple methods, consider create a typed exception (AddressException for example) to make it more accurate.

2021-01-25 03:52 UTC, Tigo9527 commented on src/main/java/conflux/web3j/types/CfxAddress.java
> +    private final String address;
Recommended to use base32address as variable name, or add comment for it.

2021-01-25 03:52 UTC, Tigo9527 commented on src/main/java/conflux/web3j/types/CfxAddress.java
> +        return CfxAddress.HEX_PREFIX + BaseEncoding.base16().encode(this.addressBuffer);
Better to add a hexAddress field, avoid computing.

2021-01-25 03:52 UTC, Tigo9527 commented on src/main/java/conflux/web3j/types/CfxAddress.java
> +    public static boolean haveAddressPrefix(String cfxAddressStr) {
Recommended to use haveNetworkPrefix. `addressPrefix` is Ambiguous.

2021-01-25 03:52 UTC, Tigo9527 commented on src/main/java/conflux/web3j/types/CfxAddress.java
> +    public static String normalize(String address, int chainId) throws Exception {
`normalize` doesn't have a specific meaning. Consider `toBase32`.

2021-01-25 03:52 UTC, Tigo9527 commented on src/main/java/conflux/web3j/types/CfxAddress.java
> +        if(address == null) {
As previous one. Consider `toBase32`.

2021-01-25 06:38 UTC, Pana reviewed
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18)* status: 0 of 17 files reviewed, 5 unresolved discussions (waiting on @boqiu and @Tigo9527)

___
*[src/main/java/conflux/web3j/types/CfxAddress.java, line 10 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRc7Ul3AK74NCvN6cQ5-r1-10:-MRsFKuJ32g06Sr0MzWJ:bldvlin) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/df5584c79475e13957ff1fc405f849dcf769d98a/src/main/java/conflux/web3j/types/CfxAddress.java#L10)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

Recommended to use base32address as variable name, or add comment for it.
</blockquote></details>

add comment
___
*[src/main/java/conflux/web3j/types/CfxAddress.java, line 53 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRc7Ul3AK74NCvN6cQ5-r1-53:-MRsFohrBJ02MOzhZmxS:b-ci1qnd) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/df5584c79475e13957ff1fc405f849dcf769d98a/src/main/java/conflux/web3j/types/CfxAddress.java#L53)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

Better to add a hexAddress field, avoid computing.
</blockquote></details>

There is a hex buffer field, i think hex str is redundancy
___
*[src/main/java/conflux/web3j/types/CfxAddress.java, line 146 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRc7Ul3AK74NCvN6cQ5-r1-146:-MRsFSTM2JHeAZGUVpa8:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/df5584c79475e13957ff1fc405f849dcf769d98a/src/main/java/conflux/web3j/types/CfxAddress.java#L146)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

Recommended to use haveNetworkPrefix. `addressPrefix` is Ambiguous.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/types/CfxAddress.java, line 150 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRc7Ul3AK74NCvN6cQ5-r1-150:-MRsFUmHE8s0-vFkWNFf:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/df5584c79475e13957ff1fc405f849dcf769d98a/src/main/java/conflux/web3j/types/CfxAddress.java#L150)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

`normalize` doesn't have a specific meaning. Consider `toBase32`.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/types/CfxAddress.java, line 158 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRc7Ul3AK74NCvN6cQ5-r1-158:-MRsFevfBAHatwO3xzEa:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/df5584c79475e13957ff1fc405f849dcf769d98a/src/main/java/conflux/web3j/types/CfxAddress.java#L158)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

As previous one. Consider `toBase32`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-25 06:47 UTC, Tigo9527 reviewed
It's ok.

2021-01-25 12:29 UTC, boqiu requested changes
> Reviewed 12 of 17 files at r1, 5 of 5 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18)* status: all files reviewed, 36 unresolved discussions (waiting on @Pana and @Tigo9527)

___
*[src/main/java/conflux/web3j/Account.java, line 31 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtF0hm8B3JZf3acQrp:-MRtF0hm8B3JZf3acQrq:b1h9im1) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/Account.java#L31)):*
> ```Java
> 	private ECKeyPair ecKeyPair;
> 	
> 	private Account(Cfx cfx, String address) throws Exception {
> ```

How about to throw a runtime exception, just like current `AddressException`?
___
*[src/main/java/conflux/web3j/Account.java, line 37 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtFGkKDwZ3UGNLmOhg:-MRtFGkKDwZ3UGNLmOhh:bfnyt8m) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/Account.java#L37)):*
> ```Java
> 		} else {
> 			this.address = new CfxAddress(address, cfx.getChainId().intValue());
> 		}
> ```

Why not to provide a constructor in `CfxAddress` with 2 parameters: hex address and Cfx instance? Otherwise, all users need such code snippet.
___
*[src/main/java/conflux/web3j/Account.java, line 56 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtFeAa575XIjVBOHvo:-MRtFeAa575XIjVBOHvp:b-797ehg) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/Account.java#L56)):*
> ```Java
> 	}
> 	
> 	public static Account create(Cfx cfx, String privateKey) throws Exception {
> ```

how about to use runtime exception instead?
___
*[src/main/java/conflux/web3j/Account.java, line 68 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtFsf6-xXNwDvl9eQM:-MRtFsf6-xXNwDvl9eQN:botmrgg) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/Account.java#L68)):*
> ```Java
> 	}
> 	
> 	public String getAddress() {
> ```

Why not return the CfxAddress instance? Otherwise, client may not aware about the new address format. Strongly recommend to allow user to decide the address format.
___
*[src/main/java/conflux/web3j/AccountManager.java, line 51 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtGLgLB-NR9UPewWsX:-MRtGLgLB-NR9UPewWsY:b-xfu21m) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/AccountManager.java#L51)):*
> ```Java
> 	 * @throws IOException if failed to create the default directory.
> 	 */
> 	public AccountManager() throws Exception {
> ```

Why throws exception?
___
*[src/main/java/conflux/web3j/AccountManager.java, line 60 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtGQLH4E1VX17fATlD:-MRtGQLH4E1VX17fATlE:b-xfu21m) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/AccountManager.java#L60)):*
> ```Java
> 	 * @throws IOException if failed to create directories.
> 	 */
> 	public AccountManager(String dir)throws Exception {
> ```

Why throws exception?
___
*[src/main/java/conflux/web3j/AccountManager.java, line 185 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtGblZ90RhrEm_QSoS:-MRtGblZ90RhrEm_QSoT:bxdhgo5) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/AccountManager.java#L185)):*
> ```Java
> 	 * @return <code>true</code> if the specified account address is managed. Otherwise, <code>false</code>.
> 	 */
> 	public boolean exists(String address) throws Exception {
> ```

Suggest to throw runtime exception for new address, and do not change the exception signature here.
___
*[src/main/java/conflux/web3j/AccountManager.java, line 247 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtH1ue1twLz6SOp9aC:-MRtH1ue1twLz6SOp9aD:b1mbwif) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/AccountManager.java#L247)):*
> ```Java
> 	 * @return private key if account exists. Otherwise, <code>null</code>.
> 	 */
> 	public String exportPrivateKey(String address, String password) throws Exception {
> ```

In my mind, this method already added in previous pull request, please double confirm?
___
*[src/main/java/conflux/web3j/Conflux.java, line 13 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtHT_K971Gw7SgHuxn:-MRtHT_K971Gw7SgHuxo:bj0zcy6) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/Conflux.java#L13)):*
> ```Java
> 
> 
> public interface Conflux extends Cfx {
> ```

Why not reuse the existing Cfx interface and add overloaded methods? Otherwise, dapp need to change all the code that referenced`Cfx` type.
___
*[src/main/java/conflux/web3j/crypto/ConfluxBase32.java, line 5 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtNHBUD6_O5B_akN9j:-MRtNHBUD6_O5B_akN9k:b-gugk5l) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/crypto/ConfluxBase32.java#L5)):*
> ```Java
> import java.util.HashMap;
> 
> public class ConfluxBase32 {
> ```

Better to add necessary comment, e.g. cip link
___
*[src/main/java/conflux/web3j/crypto/ConfluxBase32.java, line 6 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtNPfACL268Ftf2hXp:-MRtNPfB8KeFrC9e5AUI:b6uacgd) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/crypto/ConfluxBase32.java#L6)):*
> ```
> ADDRESS_CHARSET
> ```

How about to use `CONFLUX_CHARSET` or `CFX_CHARSET`?
___
*[src/main/java/conflux/web3j/crypto/ConfluxBase32.java, line 10 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtNYnwBL-PXZxcAWaY:-MRtNYnwBL-PXZxcAWaZ:b2ez13q) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/crypto/ConfluxBase32.java#L10)):*
> ```Java
>     private static final char PADDING_CHAR = '=';
> 
>     private static final HashMap<Character, Integer> ADDRESS_CHAR_MAP = new HashMap<>(){{
> ```

Better to use java 8 syntax instead.
___
*[src/main/java/conflux/web3j/crypto/ConfluxBase32.java, line 32 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtOwD-9cDNMSXoAlJG:-MRtOwD-9cDNMSXoAlJH:br2qrxo) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/crypto/ConfluxBase32.java#L32)):*
> ```Java
>     public static String encode(byte[] buffer) throws CfxBase32Exception {
>         if (buffer == null) {
>             throw new CfxBase32Exception("Invalid arguments");
> ```

throw `NullPointerException` or with correct error message "buffer is null or empty"?
___
*[src/main/java/conflux/web3j/crypto/ConfluxBase32.java, line 70 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtOcRqBtmvpQ5DvYGV:-MRtOcRqBtmvpQ5DvYGW:b-hvscpw) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/crypto/ConfluxBase32.java#L70)):*
> ```
> checkChars
> ```

Generally, `isValid()` returns `bool`, `checkXxx` or `validateXxx` throws exception.
___
*[src/main/java/conflux/web3j/crypto/ConfluxBase32.java, line 71 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtPIAuAFGHBdK41KzJ:-MRtPIAu [...]

2021-01-26 01:23 UTC, Pana reviewed
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18)* status: 12 of 23 files reviewed, 36 unresolved discussions (waiting on @boqiu, @Pana, and @Tigo9527)

___
*[src/main/java/conflux/web3j/Account.java, line 31 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtF0hm8B3JZf3acQrp:-MRwGR4H1gH0m8KGRJTc:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/Account.java#L31)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

How about to throw a runtime exception, just like current `AddressException`?
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/Account.java, line 37 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtFGkKDwZ3UGNLmOhg:-MRw82TP80JSMJdhYHm0:b-aft0iu) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/Account.java#L37)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not to provide a constructor in `CfxAddress` with 2 parameters: hex address and Cfx instance? Otherwise, all users need such code snippet.
</blockquote></details>

why a user need create a Address with a Cfx instance ?
___
*[src/main/java/conflux/web3j/Account.java, line 56 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtFeAa575XIjVBOHvo:-MRwGTKv9lJzTPyXOQvU:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/Account.java#L56)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

how about to use runtime exception instead?
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/Account.java, line 68 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtFsf6-xXNwDvl9eQM:-MRw8GcHEIQ5lhv4WKU4:b-3thpbi) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/Account.java#L68)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not return the CfxAddress instance? Otherwise, client may not aware about the new address format. Strongly recommend to allow user to decide the address format.
</blockquote></details>

Why would you get a CfxAddress instannce from a CfxAddress instance ?
___
*[src/main/java/conflux/web3j/AccountManager.java, line 51 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtGLgLB-NR9UPewWsX:-MRwGXN27O3LLShMgUyF:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/AccountManager.java#L51)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why throws exception?
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/AccountManager.java, line 60 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtGQLH4E1VX17fATlD:-MRwGXwp3Qp3ytmfI8Fe:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/AccountManager.java#L60)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why throws exception?
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/AccountManager.java, line 247 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtH1ue1twLz6SOp9aC:-MRwG_Dt276RfxQL7rkc:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/AccountManager.java#L247)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

In my mind, this method already added in previous pull request, please double confirm?
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/Conflux.java, line 13 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtHT_K971Gw7SgHuxn:-MRwGcd7-ZJKOMaJ_5S2:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/Conflux.java#L13)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not reuse the existing Cfx interface and add overloaded methods? Otherwise, dapp need to change all the code that referenced`Cfx` type.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/crypto/ConfluxBase32.java, line 5 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtNHBUD6_O5B_akN9j:-MRwGfJl4mCfCrKDFdbq:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/crypto/ConfluxBase32.java#L5)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Better to add necessary comment, e.g. cip link
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/crypto/ConfluxBase32.java, line 6 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtNPfACL268Ftf2hXp:-MRwGg-zBL7I336OIQO2:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/crypto/ConfluxBase32.java#L6)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> ADDRESS_CHARSET
> ```

How about to use `CONFLUX_CHARSET` or `CFX_CHARSET`?
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/crypto/ConfluxBase32.java, line 32 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtOwD-9cDNMSXoAlJG:-MRwGhJ31K6r1uP4kaHo:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/crypto/ConfluxBase32.java#L32)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

throw `NullPointerException` or with correct error message "buffer is null or empty"?
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/crypto/ConfluxBase32.java, line 70 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtOcRqBtmvpQ5DvYGV:-MRwGigv9nvEUabmzL3t:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/crypto/ConfluxBase32.java#L70)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> checkChars
> ```

Generally, `isValid()` returns `bool`, `checkXxx` or `validateXxx` throws exception.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/crypto/ConfluxBase32.java, line 71 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtPIAuAFGHBdK41KzJ:-MRwGjtx5ywGhbyXvZY6:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/crypto/ConfluxBase32.java#L71)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

return `false` for `null` input?
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/crypto/ConfluxBase32.java, line 104 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtO2SH9HF86uIjYXgo:-MRwGlLME5InmzpuxA_b:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/crypto/ConfluxBase32.java#L104)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Should be `public`, since it is used in many public method in `ConfluxBase32` class.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/types/Address.java, line 11 at r3](htt [...]

2021-01-26 03:01 UTC, boqiu requested changes
> Reviewed 12 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18)* status: all files reviewed, 18 unresolved discussions (waiting on @Pana and @Tigo9527)

___
*[src/main/java/conflux/web3j/Account.java, line 37 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtFGkKDwZ3UGNLmOhg:-MRwXmJl8ldRWRLCDZ7q:birc7ga) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/Account.java#L37)):*
<details><summary><i>Previously, Pana (W) wrote…</i></summary><blockquote>

why a user need create a Address with a Cfx instance ?
</blockquote></details>

Or you can provide a constructor with `address` and `networkId`, since the `if-else` code snippet is common to all SDK users.
___
*[src/main/java/conflux/web3j/Account.java, line 68 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtFsf6-xXNwDvl9eQM:-MRwYJl43r2G4X3Z6xpv:b-4yqs4m) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/Account.java#L68)):*
<details><summary><i>Previously, Pana (W) wrote…</i></summary><blockquote>

Why would you get a CfxAddress instannce from a CfxAddress instance ?
</blockquote></details>

This is `Account` class, not `CfxAddress`.
___
*[src/main/java/conflux/web3j/Cfx.java, line 83 at r4](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRw_cQ4CTO23wc_z0EF:-MRw_cQ4CTO23wc_z0EG:b-onscu7) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/c0e6e687481ba78a7489e676ffbf1aac85b06a35/src/main/java/conflux/web3j/Cfx.java#L83)):*
> ```Java
> 	 * @return
> 	 */
> 	Request<BigInteger, BigIntResponse> getNonce(String address, Epoch... epoch);
> ```

Why not remove this deprecated method? Better to keep consistency for all methods.
___
*[src/main/java/conflux/web3j/Web3j.java, line 46 at r4](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRwaks83EK_udV23krC:-MRwaks83EK_udV23krD:bqs059x) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/c0e6e687481ba78a7489e676ffbf1aac85b06a35/src/main/java/conflux/web3j/Web3j.java#L46)):*
> ```Java
> 	}
> 
> 	public BigInteger getNetworkId() {
> ```

Suggest to keep the original `getChainId` method, which also helpful to sign a transaction.
___
*[src/main/java/conflux/web3j/types/AddressType.java, line 8 at r4](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRwcI3kAonoXbE2t7OE:-MRwcI3kAonoXbE2t7OF:b-5xhtur) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/c0e6e687481ba78a7489e676ffbf1aac85b06a35/src/main/java/conflux/web3j/types/AddressType.java#L8)):*
> ```
> Null
> ```

Is it necessary?


<!-- Sent from Reviewable.io -->

2021-01-26 03:02 UTC, boqiu reviewed
> Reviewed 1 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18)* status: all files reviewed, 18 unresolved discussions (waiting on @Pana and @Tigo9527)



<!-- Sent from Reviewable.io -->

2021-01-26 03:10 UTC, Tigo9527 reviewed
Use constant field since they are already defined.

2021-01-26 03:10 UTC, Tigo9527 commented on src/main/java/conflux/web3j/crypto/ConfluxBase32.java
> +    private static final HashMap<Character, Integer> CONFLUX_CHAR_MAP = new HashMap<Character, Integer>(){{
Consider using a loop to reduce hard code.

2021-01-26 03:10 UTC, Tigo9527 commented on src/main/java/conflux/web3j/types/Address.java
> +            case 1029:
Use constant instead of a magic number.

2021-01-26 03:10 UTC, Tigo9527 commented on src/main/java/conflux/web3j/types/Address.java
> +                return 1029;
Use constant field.

2021-01-26 10:27 UTC, Tigo9527 reviewed
ok.

2021-01-26 10:27 UTC, Tigo9527 commented on src/main/java/conflux/web3j/response/Status.java
> +		return Numeric.decodeQuantity(this.chainId);
Remember to fix it.

2021-01-27 00:35 UTC, Pana reviewed
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18)* status: 9 of 40 files reviewed, 22 unresolved discussions (waiting on @boqiu and @Tigo9527)

___
*[src/main/java/conflux/web3j/Account.java, line 37 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtFGkKDwZ3UGNLmOhg:-MRwf2VH1hGNHl59UyYC:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/Account.java#L37)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Or you can provide a constructor with `address` and `networkId`, since the `if-else` code snippet is common to all SDK users.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/Account.java, line 68 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtFsf6-xXNwDvl9eQM:-MS0Eyqk5pNZRb2DoYwT:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/Account.java#L68)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

This is `Account` class, not `CfxAddress`.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/AccountManager.java, line 185 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtGblZ90RhrEm_QSoS:-MS0FCc11lnvEc1R7vg6:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/AccountManager.java#L185)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Suggest to throw runtime exception for new address, and do not change the exception signature here.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/Cfx.java, line 83 at r4](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRw_cQ4CTO23wc_z0EF:-MS0FE6L5wXzVJgLGsQc:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/c0e6e687481ba78a7489e676ffbf1aac85b06a35/src/main/java/conflux/web3j/Cfx.java#L83)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not remove this deprecated method? Better to keep consistency for all methods.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/Web3j.java, line 46 at r4](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRwaks83EK_udV23krC:-MRwf9r98V85dnDFblW-:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/c0e6e687481ba78a7489e676ffbf1aac85b06a35/src/main/java/conflux/web3j/Web3j.java#L46)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Suggest to keep the original `getChainId` method, which also helpful to sign a transaction.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/crypto/ConfluxBase32.java, line 10 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtNYnwBL-PXZxcAWaY:-MRwfAjN42ilX0oBJqde:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/crypto/ConfluxBase32.java#L10)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Better to use java 8 syntax instead.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/crypto/ConfluxBase32.java, line 14 at r4](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRc7Ul3AK74NCvN6cQ4-r4-14:-MRwfCAk9jVj2ALC5_jk:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/c0e6e687481ba78a7489e676ffbf1aac85b06a35/src/main/java/conflux/web3j/crypto/ConfluxBase32.java#L14)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

Consider using a loop to reduce hard code.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/response/Status.java, line 35 at r5](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRwGJx8BZE9kqxR6IBB-r5-35:-MS0FIpL0Qyb1sNYMcle:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/ba6d1c8e49f270e40e03d16a3376f7eaf58e41fc/src/main/java/conflux/web3j/response/Status.java#L35)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

Remember to fix it.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/types/Address.java, line 213 at r4](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRc7Ul3AK74NCvN6cQ--r4-213:-MRwfQH-7q_buI5UPp4O:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/c0e6e687481ba78a7489e676ffbf1aac85b06a35/src/main/java/conflux/web3j/types/Address.java#L213)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

Use constant instead of a magic number.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/types/Address.java, line 226 at r4](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRc7Ul3AK74NCvN6cQ--r4-226:-MRwfRv9ANtUs4Fwj5zV:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/c0e6e687481ba78a7489e676ffbf1aac85b06a35/src/main/java/conflux/web3j/types/Address.java#L226)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

Use constant field.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/types/AddressType.java, line 8 at r4](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRwcI3kAonoXbE2t7OE:-MRwfZ8j-O9DOVo6R9YX:b-vptekx) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/c0e6e687481ba78a7489e676ffbf1aac85b06a35/src/main/java/conflux/web3j/types/AddressType.java#L8)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> Null
> ```

Is it necessary?
</blockquote></details>

the zero address's type is null
___
*[src/main/java/conflux/web3j/types/CfxAddress.java, line 10 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRc7Ul3AK74NCvN6cQ5-r1-10:-MRwfg94B-4e30WGFpmN:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/df5584c79475e13957ff1fc405f849dcf769d98a/src/main/java/conflux/web3j/types/CfxAddress.java#L10)):*
<details><summary><i>Previously, Pana (W) wrote…</i></summary><blockquote>

add comment
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/types/CfxAddress.java, line 53 at r1](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRc7Ul3AK74NCvN6cQ5-r1-53:-MRwfha04C1Ey9oEHzhn:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/df5584c79475e13957ff1fc405f849dcf769d98a/src/main/java/conflux/web3j/types/CfxAddress.java#L53)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Agree with Jianhu, that calculate the hex address in constructor, and just return a field in this getter method.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/types/CfxAddress.java, line 40 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtSP_m8h0khch2xvHF:-MS0FNqn3sFr3YJndL34:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/types/CfxAddress.java#L40)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

> ```
> getAddress
> ```

Better to add necessary comment that returns a standard base32 address.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/types/CfxAddress.java, line 68 at r3](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRtTo69DL1DsFr2dhIN:-MS0FTQcCHNo8iDnLRgd:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/1b51d64dae6add5d01db725859c137a8c26ae692/src/main/java/conflux/web3j/types/CfxAddress.java#L68)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not define a `static final Cf [...]

2021-01-27 03:13 UTC, boqiu requested changes
> Reviewed 2 of 7 files at r5, 29 of 29 files at r6.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18)* status: all files reviewed, 11 unresolved discussions (waiting on @Pana and @Tigo9527)

___
*[src/main/java/conflux/web3j/Web3j.java, line 223 at r6](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MS0nw71DnZNddJzvnVp:-MS0nw71DnZNddJzvnVq:b-mda7tz) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/52a8610a0040393fe857187c884be2c0239021af/src/main/java/conflux/web3j/Web3j.java#L223)):*
> ```Java
> 	public Request<String, StringResponse> call(Call request, Epoch... epoch) {
> 		if (epoch.length == 0) {
> 			System.out.println(request);
> ```

Should not print anything in SDK.
___
*[src/main/java/conflux/web3j/contract/ContractCall.java, line 90 at r6](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MS0o1jNBOp-nnoP_sm2:-MS0o1jNBOp-nnoP_sm3:b-mcp3rb) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/52a8610a0040393fe857187c884be2c0239021af/src/main/java/conflux/web3j/contract/ContractCall.java#L90)):*
> ```Java
> 	public <D, T extends Type<D>> D callAndGet(Class<T> returnType, String method, Type<?>... args) {
> 		System.out.println(method);
> 		System.out.println(args);
> ```

Should not print anything in sdk.


<!-- Sent from Reviewable.io -->

2021-01-27 03:23 UTC, Tigo9527 requested changes

2021-01-27 03:23 UTC, Tigo9527 commented on src/main/java/conflux/web3j/Web3j.java
> +			System.out.println(request);
Remove debug code.

2021-01-27 03:23 UTC, Tigo9527 commented on src/main/java/conflux/web3j/contract/ContractCall.java
> +		System.out.println(args);
Remove debug code.

2021-01-27 03:23 UTC, Tigo9527 commented on src/main/java/conflux/web3j/types/Address.java
> +    public static final byte[] ADDRESS_NULL = new byte[]{
byte[] is filled by 0 by default. so only declare the length is enough.

2021-01-27 08:24 UTC, Pana reviewed
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18)* status: 33 of 40 files reviewed, 14 unresolved discussions (waiting on @boqiu and @Tigo9527)

___
*[src/main/java/conflux/web3j/Web3j.java, line 223 at r6](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRc7Ul3AK74NCvN6cPz-r6-223:-MS0vIVF8RpFMlsA8vX6:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/52a8610a0040393fe857187c884be2c0239021af/src/main/java/conflux/web3j/Web3j.java#L223)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

Remove debug code.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/Web3j.java, line 223 at r6](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MS0nw71DnZNddJzvnVp:-MS0vJ6D6jTHh6uHBGFe:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/52a8610a0040393fe857187c884be2c0239021af/src/main/java/conflux/web3j/Web3j.java#L223)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Should not print anything in SDK.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/contract/ContractCall.java, line 90 at r6](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRsHlaHgVq6D2bDwhVO-r6-90:-MS0vNBjE11HHbaWCnG-:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/52a8610a0040393fe857187c884be2c0239021af/src/main/java/conflux/web3j/contract/ContractCall.java#L90)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

Remove debug code.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/contract/ContractCall.java, line 90 at r6](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MS0o1jNBOp-nnoP_sm2:-MS0vNWT3y-Iu4F7VtGO:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/52a8610a0040393fe857187c884be2c0239021af/src/main/java/conflux/web3j/contract/ContractCall.java#L90)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Should not print anything in sdk.
</blockquote></details>

Done.
___
*[src/main/java/conflux/web3j/types/Address.java, line 84 at r6](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRc7Ul3AK74NCvN6cQ--r6-84:-MS0vaQFCKG1Jep258a4:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/52a8610a0040393fe857187c884be2c0239021af/src/main/java/conflux/web3j/types/Address.java#L84)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

byte[] is filled by 0 by default. so only declare the length is enough.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-27 09:37 UTC, boqiu approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-:-MS2C2V9Eby3JQXDQfe2:bnfp4nl)* status: all files reviewed, 12 unresolved discussions (waiting on @Tigo9527)



<!-- Sent from Reviewable.io -->

2021-01-27 10:19 UTC, Tigo9527 approved these changes

2021-01-27 10:19 UTC, Tigo9527 commented on CHANGELOG.md
> +6. ERC20Call, ERC20Executor, ERC777Call, ERC777Executor has been removed.
Need to tell users the replacement if things are removed.

2021-01-27 11:24 UTC, Pana reviewed
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18)* status: 37 of 40 files reviewed, 13 unresolved discussions (waiting on @boqiu and @Tigo9527)

___
*[CHANGELOG.md, line 8 at r7](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRc7Ul3AK74NCvN6cPt-r7-8:-MS2_XnU8L9Y6jrtn-Ry:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/fefbca6f90e9ac1ce2c31559153fb44e0d2ec2b6/CHANGELOG.md#L8)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

Need to tell users the replacement if things are removed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-28 02:08 UTC, Tigo9527 approved these changes
Better to Use IOExceptin in the method declaration.

2021-01-28 02:08 UTC, Tigo9527 commented on src/main/java/conflux/web3j/AccountManager.java
> +	public AccountManager(String dir, int networkId) throws Exception {
Wrapping IOException to IllegalArgumentException is not necessary. Throws IOException directly, instead.

2021-01-29 01:54 UTC, Pana reviewed
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18)* status: 37 of 40 files reviewed, 14 unresolved discussions (waiting on @boqiu and @Tigo9527)

___
*[src/main/java/conflux/web3j/AccountManager.java, line 63 at r8](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-MRc7Ul3AK74NCvN6cPx-r8-63:-MSAqOrw7VPX66eLK751:b-896fix) ([raw file](https://github.com/conflux-chain/java-conflux-sdk/blob/dc256a031211af4a7fe78d21d9a482da827888d0/src/main/java/conflux/web3j/AccountManager.java#L63)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

Wrapping IOException to IllegalArgumentException is not necessary. Throws IOException directly, instead.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-29 02:01 UTC, Pana reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/18#-:-MSArxPn4x1_HFTI0bc_:bnfp4nl)* status: 37 of 40 files reviewed, 14 unresolved discussions (waiting on @boqiu and @Tigo9527)



<!-- Sent from Reviewable.io -->

2021-01-29 02:04 UTC, merged